### PR TITLE
Generate QR codes locally

### PR DESCRIPTION
**Pull request by gersomonline**
As requested by #114, this PR uses the [zxing](https://github.com/zxing/zxing) library to generate QR codes.
Checklist:

- [ ] Merge LielAmar/LielsUtils#15
- [ ] Implement an alternative for the clickable message, as we no longer have a URL. (See [AuthHandler.java#277](https://github.com/GersomR-afk/2FA/commit/91986304f9183727529338015da612f08d653c93#diff-85101d54db442d76eeea7d70bebd698fd6a5e6ace89365907911a532a4aa6d57R277))

### CODE REVIEW

**Comment by GersomR-afk** [comment]
In order to build, build my [**GersomR-afk/LielsUtils**](https://github.com/GersomR-afk/LielsUtils) fork, and place the jar inside a new directory called ``libs``.

**Comment by rudde0** [comment]
@gersomonline, could you share the jar of your work? I'm struggling with building.

**Comment by gersomonline** [comment]
> @gersomonline, could you share the jar of your work? I'm struggling with building.

I won't be able to build a jar for at least a couple of days. However, in a previous comment I mentioned how one can build my modified 2FA plugin. Please let me know what stops you from building the plugin, so I can better help you.

**Comment by LielAmar** [comment]
Closing this MR. We're currently working on a new version which should allow users to compile custom jars, as well as adding built-in support for local QR generation.

**Pull request closed without merging**
